extensions = ['cu', 'h', 'c', 'py', 'log', 'md']
folders = [

    
    # "~/projects/openssl/include/openssl/ec.h",
    # "~/projects/openssl/include/openssl/bn.h",
    # "~/projects/openssl/crypto/ec/ec_lib.c",
    # "~/projects/openssl/crypto/bn/bn_mont.c",
    "~/projects/openssl/crypto/bn/bn_mod.c",
    # "~/projects/openssl/crypto/ec/ec_mult.c",
    
    # "~/projects/openssl/crypto/ec/ec_local.h",
    # "~/projects/openssl/crypto/ec/ecp_smpl.c",

    # "~/projects/openssl/crypto/ec/ecp_mont.c",
    # "~/projects/openssl/crypto/bn/bn_sparc.c",
    # "~/projects/openssl/crypto/bn/bn_ppc.c",
    # "~/projects/openssl/crypto/bn/bn_asm.c",
    # "~/projects/openssl/crypto/bn/bn_exp.c",

    # "~/projects/avax-pw-crack/openssl/tests/ec_point_scalar_mul_montgomery/test.c",
    # "~/projects/avax-pw-crack/openssl/tests/ec_point_scalar_mul_montgomery/run.log",
    # "~/projects/avax-pw-crack/openssl/tests/BN_mod_mul_montgomery/test.c",
    # "~/projects/avax-pw-crack/openssl/tests/BN_mod_mul_montgomery/run.log",
    
    # "~/projects/avax-pw-crack/openssl/tests/ec_point_ladder_step/test.c",
    # "~/projects/avax-pw-crack/openssl/tests/ec_point_ladder_step/run.log",
    # "~/projects/avax-pw-crack/openssl/tests/bn_mod_add_fixed_top/test.c",
    # "~/projects/avax-pw-crack/openssl/tests/bn_mod_add_fixed_top/build.log",
    "~/projects/avax-pw-crack/openssl/tests/BN_mod_add_quick/test.c",
    "~/projects/avax-pw-crack/openssl/tests/BN_mod_add_quick/build.log",
    
    # "~/projects/avax-pw-crack/openssl/tests/BN_mod_exp_mont/test.c",
    # "~/projects/avax-pw-crack/openssl/tests/BN_mod_exp_mont/build.log",
    # "~/projects/avax-pw-crack/openssl/tests/BN_mod_exp_mont/run.log",
    # "~/projects/avax-pw-crack/openssl/tests/ec_point_scalar_mul_montgomery/test.c",
    # "~/projects/avax-pw-crack/openssl/tests/ec_point_scalar_mul_montgomery/run.log",

    # "~/projects/avax-pw-crack/cuda/prompts/113_EC_POINT_mul_request_b.md",
    # "~/projects/avax-pw-crack/cuda/prompts/114_EC_POINT_mul_base.md",
    # "~/projects/avax-pw-crack/cuda/prompts/112_bn_mul_mont_fixed_top.md",
    # "~/projects/avax-pw-crack/cuda/prompts/117_ec_point_ladder_step_ossl_small_sample.md",

    # "../include/",
    "~/projects/avax-pw-crack/cuda/include/bignum.h",
    # "~/projects/avax-pw-crack/cuda/include/jacobian_point.h",
    # "~/projects/avax-pw-crack/cuda/include/montgomery.h",
    # "~/projects/avax-pw-crack/cuda/include/point.h",
    # "~/projects/avax-pw-crack/cuda/include/public_key.h",
    # "~/projects/avax-pw-crack/cuda/tests/ec_point_scalar_mul_montgomery/run.log",
    # "~/projects/avax-pw-crack/cuda/tests/BN_mod_exp_mont/test.cu",
    # "~/projects/avax-pw-crack/cuda/tests/BN_mod_exp_mont/build.log",
    # "~/projects/avax-pw-crack/cuda/tests/BN_mod_exp_mont/run.log",
    # "~/projects/avax-pw-crack/cuda/tests/BN_mod_mul_montgomery_cuda/test.cu",
    # "~/projects/avax-pw-crack/cuda/tests/ec_point_scalar_mul_montgomery/test.cu",
    # "~/projects/avax-pw-crack/cuda/tests/ec_point_scalar_mul_montgomery/run.log",
    "~/projects/avax-pw-crack/python/tests/bn_mul_mod_montgomery/test.py",
    "~/projects/avax-pw-crack/python/tests/bn_mul_mod_montgomery/run.log",
    # "~/projects/avax-pw-crack/cuda/tests/ec_point_scalar_mul_montgomery/test.cu",
    # "~/projects/avax-pw-crack/cuda/tests/ec_point_scalar_mul_montgomery/run.log",
    # "~/projects/avax-pw-crack/cuda/tests/bn_div/test.cu",
    # "~/projects/avax-pw-crack/cuda/tests/BN_mod_mul_montgomery_cuda/test.cu",
    # "~/projects/avax-pw-crack/cuda/tests/BN_mod_mul_montgomery_cuda/run.log",
    # "~/projects/avax-pw-crack/openssl/tests/ec_point_ladder_step/test.c",
    # "~/projects/avax-pw-crack/openssl/tests/ec_point_ladder_step/run.log",
    # "~/projects/avax-pw-crack/cuda/tests/ec_point_ladder_step/test.cu",
    # "~/projects/avax-pw-crack/cuda/tests/ec_point_ladder_step/run.log",
    # "../main.cu",
    # "../logs/run.log",
    # "~/projects/avax-pw-crack/cuda/prompts/116_ec_point_ladder_step_base.md",
    "~/projects/avax-pw-crack/cuda/prompts/119_bn_mod_add_quick_base.md",
    ]
