FROM ubuntu:22.04

# Install build essentials, g++, and OpenSSL development packages
RUN apt-get update && apt-get install -y \
    build-essential \
    g++ \
    libssl-dev \
    nlohmann-json3-dev \
    bc

WORKDIR /app
COPY openssl/main.c .
COPY openssl/child_key.h .
RUN g++ \
    main.c \
    -std=c++11 \
    -I ../json \
    -l:libcrypto.so.3 \
    -o program

# Using shell form to execute multiple commands
CMD start_time=$(date +%s.%N) \
    && ./program \
    && end_time=$(date +%s.%N) \
    && echo $start_time \
    && echo $end_time \
    && echo "$end_time - $start_time" | bc > time.txt

# Using exec form with shell to execute multiple commands
# CMD ["/bin/bash", "-c", "start_time=$(date +%s.%N) && ./program && end_time=$(date +%s.%N) && echo $start_time && echo $end_time && echo \"$end_time - $start_time\" | bc > time.txt"]